# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName("root")
        root.resize(617, 558)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(root.sizePolicy().hasHeightForWidth())
        root.setSizePolicy(sizePolicy)
        root.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(root)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video = QtWidgets.QWidget(root)
        self.video.setFocusPolicy(QtCore.Qt.NoFocus)
        self.video.setStyleSheet("background-color: rgb(117, 80, 123);")
        self.video.setObjectName("video")
        self.verticalLayout.addWidget(self.video)
        self.widget = QtWidgets.QWidget(root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(9, 3, 9, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keep = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keep.sizePolicy().hasHeightForWidth())
        self.keep.setSizePolicy(sizePolicy)
        self.keep.setFocusPolicy(QtCore.Qt.NoFocus)
        self.keep.setChecked(True)
        self.keep.setObjectName("keep")
        self.horizontalLayout_2.addWidget(self.keep)
        self.remove = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove.sizePolicy().hasHeightForWidth())
        self.remove.setSizePolicy(sizePolicy)
        self.remove.setFocusPolicy(QtCore.Qt.NoFocus)
        self.remove.setToolTip("")
        self.remove.setStatusTip("")
        self.remove.setObjectName("remove")
        self.horizontalLayout_2.addWidget(self.remove)
        self.status = QtWidgets.QLabel(self.widget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        spacerItem = QtWidgets.QSpacerItem(383, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.encode = QtWidgets.QCheckBox(self.widget)
        self.encode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.encode.setObjectName("encode")
        self.horizontalLayout_2.addWidget(self.encode)
        self.twoPass = QtWidgets.QCheckBox(self.widget)
        self.twoPass.setCheckable(True)
        self.twoPass.setChecked(True)
        self.twoPass.setObjectName("twoPass")
        self.horizontalLayout_2.addWidget(self.twoPass)
        self.toggleArgsEdit = QtWidgets.QToolButton(self.widget)
        self.toggleArgsEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toggleArgsEdit.setObjectName("toggleArgsEdit")
        self.horizontalLayout_2.addWidget(self.toggleArgsEdit)
        self.print = QtWidgets.QToolButton(self.widget)
        self.print.setFocusPolicy(QtCore.Qt.NoFocus)
        self.print.setObjectName("print")
        self.horizontalLayout_2.addWidget(self.print)
        self.run = QtWidgets.QToolButton(self.widget)
        self.run.setFocusPolicy(QtCore.Qt.NoFocus)
        self.run.setObjectName("run")
        self.horizontalLayout_2.addWidget(self.run)
        self.verticalLayout.addWidget(self.widget)
        self.argsEdit = QtWidgets.QPlainTextEdit(root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argsEdit.sizePolicy().hasHeightForWidth())
        self.argsEdit.setSizePolicy(sizePolicy)
        self.argsEdit.setMaximumSize(QtCore.QSize(16777215, 90))
        self.argsEdit.setObjectName("argsEdit")
        self.verticalLayout.addWidget(self.argsEdit)
        self.seekbar = QtWidgets.QWidget(root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seekbar.sizePolicy().hasHeightForWidth())
        self.seekbar.setSizePolicy(sizePolicy)
        self.seekbar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.seekbar.setMouseTracking(True)
        self.seekbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.seekbar.setAutoFillBackground(False)
        self.seekbar.setStyleSheet("background-color: rgba(0,0,0,50);")
        self.seekbar.setObjectName("seekbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.seekbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loading = QtWidgets.QLabel(self.seekbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loading.sizePolicy().hasHeightForWidth())
        self.loading.setSizePolicy(sizePolicy)
        self.loading.setStyleSheet("background-color: none;")
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.horizontalLayout.addWidget(self.loading)
        self.verticalLayout.addWidget(self.seekbar)

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        _translate = QtCore.QCoreApplication.translate
        root.setWindowTitle(_translate("root", "ffcutter"))
        self.keep.setText(_translate("root", "Keep"))
        self.remove.setText(_translate("root", "Remove"))
        self.encode.setText(_translate("root", "Encode"))
        self.twoPass.setText(_translate("root", "2-pass"))
        self.toggleArgsEdit.setToolTip(_translate("root", "Show/hide ffmpeg arguments editor"))
        self.toggleArgsEdit.setText(_translate("root", "Edit Args"))
        self.print.setToolTip(_translate("root", "Print ffmpeg commands into terminal"))
        self.print.setText(_translate("root", "Print"))
        self.run.setToolTip(_translate("root", "Run ffmpeg commands."))
        self.run.setText(_translate("root", "Run"))
        self.argsEdit.setPlainText(_translate("root", "out: \n"
"# FFmpeg output arguments.\n"
"out-args: \n"
"# FFmpeg Input arguments.\n"
"in-args: "))
        self.loading.setText(_translate("root", "Loading..."))

